/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testteo;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author miiky
 */
public class Picture extends javax.swing.JFrame {

    /**
     * Creates new form picture
     */
    public Picture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Picture().setVisible(true);
            }
        });
    }
    public void paint(Graphics g){
        super.paint(g);
        // fondo de imagen
        g.setColor(Color.BLACK);
        g.fillRect(0, 0, 1200, 800);
        // pacman -Syu
        g.setColor(Color.yellow);
        g.fillArc(50, 200, 100, 100, 45, 270);
        //g.fillOval(50, 200, 100, 100);
        //g.setColor(Color.BLACK);
        //int[] mouthx = {70, 200, 200};
        //int[] mouthy = {250, 200, 300};
        //g.fillPolygon(mouthx, mouthy, 3);
        // Pac-dots
        g.setColor(Color.WHITE);
        g.fillRect(200, 245, 10, 10);
        g.fillRect(250, 245, 10, 10);
        g.fillRect(300, 245, 10, 10);
        g.fillRect(350, 245, 10, 10);
        g.fillRect(400, 245, 10, 10);
        // fantasmas
        g.setColor(Color.MAGENTA);
        Ghost pink = new Ghost(450, 200, g, 1);
        g.setColor(Color.CYAN);
        Ghost cyan = new Ghost(600, 200, g, 3);
        g.setColor(new Color(255, 115, 45));
        Ghost orange = new Ghost(750, 200, g, 4);
        g.setColor(Color.RED);
        Ghost red = new Ghost(900, 200, g, 2);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

